name: Run Python Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Install pylint
        run: uv pip install pylint

      - name: Run pylint
        run: |
          pylint --fail-under=7.5 artifact/          
      
      - name: Activate and run tests
        run: |          
          python -m unittest tests/test_inference.py
          python -m unittest tests/test_utilities.py
          python -m unittest tests/test_widgets.py
          python -m unittest tests/test_artifact.py