name: Verify whatifact

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Install pylint
        run: uv pip install pylint

      - name: Run pylint
        run: pylint --fail-under=7.5 whatifact/          
      
      - name: Activate and run tests
        run: python -m unittest discover tests

  publish-to-testpypi:
      name: Publish to TestPyPI
      runs-on: ubuntu-latest
      needs: build # ensure build job completes successfully
      if: github.ref == 'refs/heads/dev' # Only run on pushes to the dev branch
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11' # or any python version you want to use for packaging.

        - name: Install build and twine
          run: uv pip install build twine

        - name: Build package
          run: uv build

        - name: Publish package to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{secrets.TEST_PYPI_API_TOKEN}}
            repository_url: https://test.pypi.org/legacy/